### PR TITLE
ci: move away from differential shellcheck

### PR DESCRIPTION
**Pull request by sadlerap**
Differential shellcheck was ignoring errors in some cases, which was causing shellcheck warnings not to be picked up.  Move away from it and use [shellcheck-sarif][1] as a SARIF provider.

[1]: https://docs.rs/crate/shellcheck-sarif/latest

### CODE REVIEW

**Review by filariow — APPROVED** [review]
LGTM

**Comment by jamacku** [comment]
@sadlerap Do you have any examples of when Differential ShellCheck ignored added defects? I would be interested, and @kdudka could be as well. Thank you.

**Comment by sadlerap** [comment]
See #63 for an example of this in action.

Maybe it's because we weren't using a `.shellcheckrc` config, and now that we've added it as of #66 and #67, `differential-shellcheck` would work for us?  I'm definitely willing to admit user error on my part :smile:.  I could give it another try; our current setup is definitely not the most efficient.

**Comment by jamacku** [comment]
Thank you for your feedback. You are right. It is the behavior described in https://github.com/konflux-workspaces/workspaces/pull/63#pullrequestreview-1987057294 because you have enabled some optional suggestions/checks locally that are not enabled by default. 

Differential ShellCheck would report the same defects when you would enable them in  `.shellcheckrc`.

**Pull request merged**
