### PR TITLE
e2e: add USE_INSECURE_TLS

### PR DESCRIPTION
**Pull request by filariow**
Signed-off-by: Francesco Ilario <filario@redhat.com>

### CODE REVIEW

**Comment by sadlerap** [comment]
Giving this a test, will have results shortly.

**Review by sadlerap — COMMENTED** [review]
Changes look LGTM, but I'm seeing some test failures when running with `USE_INSECURE_TLS=true`

```
--- Failed steps:

  Scenario: list workspaces with just default workspace # features/restapi/read.feature:3
    When The user requests the list of workspaces # features/restapi/read.feature:6
      Error: after scenario hook failed: error retrieving workspaces from host workspaces-rest-api-server-workspaces-system.apps.rosa.pec98-4kuyy-34q.aq5e.p3.openshiftapps.com as user test-22-default-user: the server is currently unable to handle the request (get internalworkspaces.workspaces.konflux.io), step error: error retrieving workspaces from host workspaces-rest-api-server-workspaces-system.apps.rosa.pec98-4kuyy-34q.aq5e.p3.openshiftapps.com as user test-22-default-user: the server is currently unable to handle the request (get internalworkspaces.workspaces.konflux.io), error retrieving workspaces from host workspaces-rest-api-server-workspaces-system.apps.rosa.pec98-4kuyy-34q.aq5e.p3.openshiftapps.com as user test-22-default-user: the server is currently unable to handle the request (get internalworkspaces.workspaces.konflux.io), step error: error retrieving workspaces from host workspaces-rest-api-server-workspaces-system.apps.rosa.pec98-4kuyy-34q.aq5e.p3.openshiftapps.com as user test-22-default-user: the server is currently unable to handle the request (get internalworkspaces.workspaces.konflux.io)

  Scenario: get workspaces with just default workspace # features/restapi/read.feature:9
    When The user requests their default workspace # features/restapi/read.feature:12
      Error: after scenario hook failed: error retrieving workspace test-27-default-user/test-27-default-user from host workspaces-rest-api-server-workspaces-system.apps.rosa.pec98-4kuyy-34q.aq5e.p3.openshiftapps.com as user test-27-default-user: the server is currently unable to handle the request (get internalworkspaces.workspaces.konflux.io test-27-default-user), step error: error retrieving workspace test-27-default-user/test-27-default-user from host workspaces-rest-api-server-workspaces-system.apps.rosa.pec98-4kuyy-34q.aq5e.p3.openshiftapps.com as user test-27-default-user: the server is currently unable to handle the request (get internalworkspaces.workspaces.konflux.io test-27-default-user), error retrieving workspace test-27-default-user/test-27-default-user from host workspaces-rest-api-server-workspaces-system.apps.rosa.pec98-4kuyy-34q.aq5e.p3.openshiftapps.com as user test-27-default-user: the server is currently unable to handle the request (get internalworkspaces.workspaces.konflux.io test-27-default-user), step error: error retrieving workspace test-27-default-user/test-27-default-user from host workspaces-rest-api-server-workspaces-system.apps.rosa.pec98-4kuyy-34q.aq5e.p3.openshiftapps.com as user test-27-default-user: the server is currently unable to handle the request (get internalworkspaces.workspaces.konflux.io test-27-default-user)

  Scenario: users can update their workspaces' visibility # features/restapi/update.feature:6
    When The user changes workspace visibility to "community" # features/restapi/update.feature:9
      Error: after scenario hook failed: the server is currently unable to handle the request (put internalworkspaces.workspaces.konflux.io test-50-default-user), step error: the server is currently unable to handle the request (put internalworkspaces.workspaces.konflux.io test-50-default-user), the server is currently unable to handle the request (put internalworkspaces.workspaces.konflux.io test-50-default-user), step error: the server is currently unable to handle the request (put internalworkspaces.workspaces.konflux.io test-50-default-user)
```

**Review by sadlerap — COMMENTED** [review]
The approach looks sound, though this needs a rebase in light of #130.

**Comment by filariow** [comment]
superseded by #148

**Pull request closed without merging**
